project_id = "wfthvovlhphnrodrqxqt"

[functions.leads-collector]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false

[functions.chat-storo]
verify_jwt = false

[functions.strcr-create-invoice]
verify_jwt = false

[functions.strcr-payment-confirm]
verify_jwt = false